from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),
    path('auth/google/', views.google_login, name='google_login'),
    path('auth/google/callback/', views.google_callback, name='google_callback'),
    path('upload/', views.upload_view, name='upload'),
    path('upload/scan/', views.upload_scan, name='upload_scan'),
    path('cases/', views.cases_list, name='cases'),
    path('profile/', views.profile_view, name='profile'),
    path('cases/<uuid:scan_id>/delete/', views.delete_scan, name='delete_scan'),
    path('analysis/<uuid:scan_id>/', views.analysis_view, name='analysis'),
    path('analysis/<uuid:scan_id>/save-notes/', views.save_notes, name='save_notes'),
    path('analysis/<uuid:scan_id>/download/', views.download_report, name='download_report'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-panel/', views.admin_analytics, name='admin_analytics'),
    path('admin-panel/scans/', views.admin_scans, name='admin_scans'),
    path('admin-panel/scans/<uuid:scan_id>/delete/', views.admin_delete_scan, name='admin_delete_scan'),
    path('admin-panel/users/', views.user_management, name='user_management'),
    path('admin-panel/users/add/', views.add_user, name='add_user'),
    path('admin-panel/users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('admin-panel/users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('admin-panel/users/<int:user_id>/toggle/', views.toggle_user_status, name='toggle_user_status'),
    path('news/', views.news_view, name='news'),
    path('news/toggle-notifications/', views.toggle_notifications, name='toggle_notifications'),
    path('news/feed/', views.news_feed_api, name='news_feed_api'),
    path('news/comments/<path:permalink>', views.news_comments_api, name='news_comments_api'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('chatbot/api/', views.chatbot_api, name='chatbot_api'),
    path('contact/', views.contact_view, name='contact'),
    path('booking/', views.booking_view, name='booking'),
]