# Generated by Django 5.2.8 on 2026-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_news_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentationresult",
            name="clinical_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="segmentationresult",
            name="recommendations_json",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="segmentationresult",
            name="tumor_location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="segmentationresult",
            name="who_grade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pendingsignup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="segmentationresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="systemstats",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
